### ISSUE TITLE
adding code of conduct file 

### ISSUE THREAD

**Issue by devxMani** [gauravsingh1281/Rentalog.in--Frontend#154]
can you add GSOC and hacktoberfest labels to this

**Comment by SatyaD012** [comment]
@SumanKisku 
 I hope this message finds you well! I would like to request your approval to be assigned to issue #182, which involves adding a CODE_OF_CONDUCT.md file to the Rentalog project.
1. To establish a Code of Conduct that fosters a welcoming and inclusive environment for all contributors.
2.I plan to use the Contributor Covenant template, which outlines the expected behavior and responsibilities of community members.
 2.This will help guide our contributors and ensure that everyone feels safe and respected in our community.
P.S: Please add gssoc-ext and hactoberfest-accepted labels

**Comment by SatyaD012** [comment]
@gauravsingh1281 
can you assign me this issue
I propose to add a CODE_OF_CONDUCT.md file to establish clear community guidelines and foster an inclusive environment for all contributors. This will enhance the contributor experience and attract a diverse range of participants to the Rentalog project.
Add GSOC and hacktoberfest labels to this

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
